name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # ou a versão que você precisa

      - name: Install npm dependencies
        run: npm install # ou 'yarn install' se você estiver usando yarn

      - name: Grant execute permission for gradlew
        run: chmod +x ./android/gradlew

      - name: Build with Gradle
        run: cd android && ./gradlew build